### ISSUE TITLE
Plugin doesn't appear in list

### ISSUE THREAD

**Issue by sjmackenzie** [bennetthardwick/rust-obs-plugins#1]
I followed the instructions using the example plugin but couldn't achieve a working result. 
Clicking on the `filters` list didn't yield the expected result. Indeed it simply wasn't there.

I'm on nixos, I've tested with `/usr/lib/obs-plugins/` along with `~/.config/obs-studio/plugins/bin/`
please advise.

**Comment by bennetthardwick** [comment]
Hey, thanks for the interest in the plugin - it seems in the instructions I was creating the symlink wrong. Instead of using a relative path, you need to use an absolute path. I've updated the instructions to reflect this. The alternate method of copying the file should have worked though.

**Comment by sjmackenzie** [comment]
Hello I didn't have a problem with the symlinks, I default to absolute paths always (prior pain).

The issue was solved with this [post](https://obsproject.com/forum/threads/solved-where-is-plugins-directory.113716/). Specifically:

`ln -s $(pwd)/target/release/libscrollfocus.so /home/$user/.config/obs-studio/plugins/scrollfocus/bin/64bit/libscrollfocus.so`

Thank you for your response, and keep safe.

**Comment by ArnoldDeRuiter** [comment]
I also have trouble getting the plugins to appear in OBS.

The two examples plugins and the basic one in the ReadMe all do not show up, they build just fine into an `.so` file though.

I am using Manjaro with 5.10 and the Official Repository (Community) OBS package.

Placing the plugin in `/usr/lib/obs-plugins/` or `home/$user/.config/obs-studio/plugins/scrollfocus/bin/64bit/libscrollfocus.so` just don't seem to make a difference to the new plugin appearing. Other plugins (StreamFS or MoveTransition) seem to work fine in the latter location.

My plugin for Looking Glass `OBSLookingGlass.so` is placed in the `/usr/lib/obs-plugins/` location and indeed does disappear when removed from there. Just nothing happens in either location with for example the Rnnoise plugin filter.

Anything I can check or info I can provide?

**Comment by bennetthardwick** [comment]
Hey @ArnoldDeRuiter sorry about the delayed reply, just to clarify when using the rnnoise plugin example you're looking at the audio filters section in the mixer and not in the video filters section?

For the example filter in the README since it doesn't implement the `VideoRenderSource` or `FilterAudioSource` traits it doesn't have anywhere to show.
