### ISSUE TITLE
Can't seem to use multiple log levels in the same plugin

### ISSUE THREAD

**Issue by ohmree** [bennetthardwick/rust-obs-plugins#21]
I've tried different configurations of `log`'s feature flags and `with_promote_debug` & `with_max_level` from this crate and have found that when I set the max log level (through `with_max_level`) to a log level `L`, instead of enabling all log levels `>=L` it enables just `L`.

The feature flags from `log` seem to have no effect on this and I think I know why (maybe they cause the disabled log functions to be left out of the shared object entirely?).

[Here's an example](https://github.com/ohmree/rust-obs-log-bug) (can reproduce on my machine :tm: ) and the relevant lines from the OBS log:

```
00:44:04.130:   Loaded Modules:
00:44:04.130:     testing.so
[a bunch of lines omitted for brevity]
00:44:14.453: (INFO) [testing] Info
00:44:14.453: User added filter 'Testing' (my_plugin_source) to source 'Desktop Audio'
```

EDIT:
```shell
$ obs --version
OBS Studio - 27.0.1-3 (linux)
```

**Comment by bennetthardwick** [comment]
Hey @ohmree sorry about the delay. I found out the issue was a dodgy if statement - it's fixed in febdd0b0c0441cd75e2d4fff7bb5c75fbd92ae1c and published as version `0.2.3`.
