### ISSUE TITLE
The docs build seems to have failed since 0.1.6

### ISSUE THREAD

**Issue by colons** [bennetthardwick/rust-obs-plugins#30]
i don't know what you can do to mitigate [this](https://docs.rs/crate/obs-wrapper/0.3.1/builds/627450). im able to build the docs locally, so it's not a huge deal, but this seems worth fixing if possible

**Comment by bennetthardwick** [comment]
Hi @colons thanks for letting me know - I can't believe I never noticed. I've fixed this up now 👍🏻
